load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "api.go",
        "errors.go",
        "type.go",
    ],
    importpath = "github.com/thelark/hyperchain-go-sdk/api",
    deps = [
    ],
    visibility = ["//visibility:public"],
)

